import type { MessageSchema } from '../../fr'

const replay: MessageSchema['pages']['replay'] = {
  untitled: 'Session',
  named: 'named',
  subagents: 'subagents',
  error: 'Transcript unreadable.',

  stats: {
    turns: 'Turns',
    turnsTip: '{you} messages / {claude} replies',
    you: 'your',
    claude: 'Claude',
    tools: 'Tools',
    toolsTip: 'Total number of tool calls (Bash, Read, Edit…) in the session',
    tokensIn: 'Tokens ↓',
    tokensInTip: '{in} tokens: the context sent to the model (cache excluded)',
    in: 'Input',
    tokensOut: 'Tokens ↑',
    tokensOutTip: '{out} tokens: the text generated by Claude',
    out: 'Output',
    cache: 'Cache',
    cacheTip: 'Tokens read from the context {cache} (reused, billed at a reduced rate)',
    cacheWord: 'cache',
    duration: 'Duration',
    durationTip: 'Time elapsed between the first and the last message of the session',
  },

  scope: {
    main: 'Main thread — subagents have their own track',
    all: 'Whole session — everything is shown',
    track: '{agent} track — {turns}',
    turns: '{n} turn | {n} turns',
    unnamed: 'subagent',
  },
  expandAll: 'Expand all',
  collapseAll: 'Collapse all',

  emptyMain: 'The main thread carries no message — all the work is in the tracks above.',
  emptyTrack: 'No message in this track.',

  aside: 'Session tasks, context and diagnostics',
  tasks: 'Tasks',
  context: 'Context window',
  diagnostic: 'Session diagnostics',
}

export default replay
